[package]
name = "artemis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
csv = "1.1.6"
filetime = "0.2.18"
indicatif = "0.17.1"
serde = { version = "1.0.147", features = ["derive"] }
sqlx = { version = "0.6.2", features = ["sqlite", "runtime-tokio-rustls"] }
tokio = { version = "1.21.2", features = ["full"] }
ureq = "2.5.0"
zip = { version = "0.6.3", default-features = false, features = ["deflate"] }
